### ISSUE TITLE
No longer maintained?

### ISSUE THREAD

**Issue by diegoiast** [andreikop/qutepart-cpp#2]
It seems this project is no longer maintain. I am working on my own fork, which compiles with Qt6, and has a few new bug fixes: https://github.com/diegoiast/qutepart-cpp/tree/qt6-port-take2

Can I take over this project? Otherwise - I strongly recommend users to use my fork, as its more active (Qt6 support, MSVC support etc).

**Comment by andreikop** [comment]
Hi
Make a MR for README.md with information about your fork and a link to your page

**Comment by diegoiast** [comment]
sure - https://github.com/andreikop/qutepart-cpp/pull/3


BTW, license is LGPLv2, but also "WTFPL". I assume that re-licensing it to MIT is accepted by you, correct?

**Comment by diegoiast** [comment]
You should archive the project if this is possible. Thanks.
